spring:
  application:
    name: my-ai-agent
  profiles:
    active: local
  ai:
    dashscope:
      chat:
        options:
          model: qwen-plus
app:
  multimodal:
    model: qwen3.5-plus
    # 可选：扩展其他配置
    enabled: true
    timeout: 60s

server:
  port: 8083
  servlet:
    context-path: /api


# springdoc-openapi????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.myaiagent.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn

